---
- name: リモートファイルをアーカイブして一括回収する
  hosts: "{{ target_node }}"
  vars:
    transaction_id: "{{ transaction_id }}"
    remote_src_dir: "/tmp/exports/{{ transaction_id }}"
    remote_archive: "/tmp/{{ inventory_hostname }}_{{ transaction_id }}.tar.gz"
    local_dest_dir: "/tmp/exports/{{ transaction_id }}/{{ inventory_hostname }}"

  tasks:
    - name: リモート側でファイルを tar.gz に固める
      community.general.archive:
        path: "."
        dest: "{{ remote_archive }}"
        format: gz
        working_dir: "{{ remote_src_dir }}"

    - name: ローカルの保存先ディレクトリを作成
      ansible.builtin.file:
        path: "{{ local_dest_dir }}"
        state: directory
      delegate_to: localhost

    - name: アーカイブファイルを1本だけ fetch する
      ansible.builtin.fetch:
        src: "{{ remote_archive }}"
        dest: "{{ local_dest_dir }}/archive.tar.gz"
        flat: yes

    - name: ローカル側で解凍する
      ansible.builtin.unarchive:
        src: "{{ local_dest_dir }}/archive.tar.gz"
        dest: "{{ local_dest_dir }}"
        remote_src: no
      delegate_to: localhost

    - name: リモートの一時ファイルを削除
      ansible.builtin.file:
        path: "{{ remote_archive }}"
        state: absent

    - name: ローカルのアーカイブファイルを削除
      ansible.builtin.file:
        path: "{{ local_dest_dir }}/archive.tar.gz"
        state: absent
      delegate_to: localhost
