- hosts: all
  vars:
    target_log: System
  tasks:
    - name: Get recent Application log events
      ansible.windows.win_shell: |
        Get-EventLog -LogName System -EntryType Error
      register: ret

    - debug: var=ret
