- hosts: all
  vars:
    target_log: System
  tasks:
    - name: Get recent Application log events
      ansible.windows.win_shell: |
        Get-WinEvent -LogName {{ target_log }} -EntryType Error -Newest 10
      register: ret

    - debug: var=ret
