- hosts: "{{ target_node }}"
  gather_facts: false
  vars:
    win_target_log: System
  tasks:
    - name: Get recent Application log events
      ansible.windows.win_shell: |
        Get-EventLog -LogName {{ win_target_log }} -EntryType Error -Newest 10 | Format-List *
      register: ret

    - debug: var=ret

    - name: export error log data to the next job template
      set_stats:
        data:
          error_source: Windows Eventlog "{{ win_target_log }}"
          error_logs: "{{ ret.stdout }}"
