- hosts: all
  tasks:
    - name: Get recent Application log events
      ansible.windows.win_shell: |
        Get-WinEvent -LogName Application -MaxEvents 10 | ConvertTo-Json
      register: application_events_json

    - name: Display Application log events
      debug:
        msg: "{{ application_events_json.stdout | from_json }}"
