---
- name: Send messages to Mattermost
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    mattermost_token: ""
    mattermost_instance: ""
    mt_text: ""
    mt_color: ""
    mt_title: ""
    mt_field_title1: ""
    mt_field_vaule1: ""
    mt_field_short1: true
    mt_field_title2: ""
    mt_field_vaule2: ""
    mt_field_short2: true

  tasks:
    - name: Fail if required variables are not set
      ansible.builtin.fail:
        msg: "Both Mattermost Instance and token must be set!"
      when: mattermost_instance | default('') | trim == '' or mattermost_token | default('') | trim == ''

    - name: Send error notification message via Mattermost
      community.general.mattermost:
        url: "{{ mattermost_instance }}"
        api_key: "{{ mattermost_token }}"
        attachments:
          - text: "{{ mt_text }}"
            color: "{{ mt_color }}"
            title: "{{ mt_title }}"
            fields:
              - title: "{{ mt_field_title1 }}"
                value: "{{ mt_field_vaule1 }}"
                short: "{{ mt_field_short1 }}"
              - title: "{{ mt_field_title2 }}"
                value: "{{ mt_field_vaule2 }}"
                short: "{{ mt_field_short2 }}"
      delegate_to: localhost
