---
- name: 移動処理の準備と実行
  hosts: all
  vars:
    src_dir: "/home/ec2-user/exports/{{ transaction_id }}"
    dest_parent: "/home/ec2-user/gemini_aiops/transactions"
    final_dest: "/home/ec2-user/gemini_aiops/transactions/{{ transaction_id }}"

  tasks:
    - name: 移動先の親ディレクトリが存在することを確認
      ansible.builtin.file:
        path: "{{ dest_parent }}"
        state: directory
        mode: '0755'

    - name: 移動元の存在確認
      ansible.builtin.stat:
        path: "{{ src_dir }}"
      register: src_stat

    - name: 移動
      ansible.builtin.shell: |
        mv {{ src_dir }}/* {{ final_dest }}
      when: src_stat.stat.exists
      register: move_result
