---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get an existing VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm_info:
        name: rhel9-vm1
        namespace: vms-aap-day2
      register: default_testvm

    - debug: var=default_testvm

    - name: Create a VirtualMachine with a DataVolume template
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: testvm-with-dv
        namespace: rhsc2025-aap
        labels:
          app: testvm-with-dv
        instancetype:
          name: u1.small
        preference:
          name: fedora
        data_volume_templates:
          - metadata:
              name: centos-stream9-coral-gecko-27
            sourceRef:
              kind: DataSource
              name: centos-stream9
              namespace: openshift-virtualization-os-images
            spec:
              storage:
                resources:
                  requests:
                    storage: 30Gi
