---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get an existing VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm_info:
        name: rhel9-vm1
        namespace: rhsc2025-aap
      register: default_testvm

    - debug: var=default_testvm

    - name: Create a VirtualMachine with a DataVolume template
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: testvm-with-dv
        namespace: rhsc2025-aap
        labels:
          app: testvm-with-dv
        data_volume_templates:
          - metadata:
              name: centos-stream9
            spec:
              sourceRef:
                kind: DataSource
                name: centos-stream9
                namespace: openshift-virtualization-os-images
              storage:
                resources:
                  requests:
                    storage: 30Gi
        spec:
          domain:
            resources:
              requests:
                memory: 2Gi
            devices:
              disks:
                - name: disk0
                  disk:
                    bus: virtio
          volumes:
            - name: disk0
              dataVolume:
                name: centos-stream9
