---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get an existing VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm_info:
        name: rhel9-vm1
        namespace: vms-aap-day2
      register: default_testvm

    - debug: var=default_testvm

    - name: Create a VirtualMachine with a DataVolume template
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: testvm-with-dv
        namespace: rhsc2025-aap
        labels:
          app: testvm-with-dv
        instancetype:
          name: u1.small
        data_volume_templates:
          - metadata:
              name: rhel9
            spec:
              sourceRef:
                kind: DataSource
                name: rhel9
                namespace: openshift-virtualization-os-images
              storage:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 30Gi
