---
- hosts: all
  gather_facts: false
  tasks:

    - name: define 1st job template
      ansible.controller.job_template:
        name: 0001_define_aap_objects
        organization: Default
        state: present
        inventory: Demo Inventory
        project: aap-demo
        playbook: aap-setup/define_aap_object.yaml
        survey_enabled: true
        credentials: aap26
        survey_spec:
          name: 定義するオブジェクトとデータソースを選択
          description: ""
          spec:
            - question_name: 定義するオブジェクトを選択
              question_description: 複数選択可
              variable: aap_target_obj
              type: multiplechoice
              choices:
                - inventory
                - credential
                - job_template
              min: 1
              max: 1
              default: inventory
              required: true
            - question_name: データソースファイルを指定
              question_description: data/xxxxx.yaml を指定する
              variable: aap_target_data
              type: text
              required: true

    - name: Custom credential for RedMine API Key
      ansible.controller.credential_type:
        name: RedMine API Key
        description: RedMine API Key を格納し、Playbookから redmine_api_key で参照可能。
        kind: cloud
        inputs:
          fields:
            - id: redmine_server_url
              type: string
              label: redmine_server_url
            - id: redmine_api_key
              type: string
              label: redmine_api_key
              secret: true
          required:
            - redmine_server_url
            - redmine_api_key
        injectors:
          extra_vars:
            redmine_server_url: "{{ '{{' }} redmine_server_url {{ '}}' }}"
            redmine_api_key: "{{ '{{' }} redmine_api_key {{ '}}' }}"
        state: present
