- hosts: all
  gather_facts: false
  vars_files:
    - "{{ aap_target_data }}"

  tasks:
    - name: define inventory
      include_tasks: define_inventories.yaml
      when: '"inventory" in aap_target_obj'
      loop: "{{ inventories.data }}"
      loop_control:
        loop_var: lp_inv
