- hosts: all
  gather_facts: false
  tasks:
    - name: define inventory
      when: "inventory" in aap_target_obj
      vars_files:
        - data_inventories.yaml
      block:
        - name: define inventories
          ansible.controller.inventory:
            name: "{{ item.inv.name }}"
            description: "{{ item.inv.description }}"
            organization: "{{ item.inv.organization | default(default.inv.organization) }}"
            state: "{{ item.inv.state | default(default.inv.state) }}"
          loop: "{{ inventories }}"
