- hosts: all
  gather_facts: false
  vars_files:
    - data_inventories.yaml

  tasks:
    - name: define inventory
      when: '"inventory" in aap_target_obj'
      block:
        - name: define inventories
          ansible.controller.inventory:
            name: "{{ item.inv.name }}"
            description: "{{ item.inv.description }}"
            organization: "{{ item.inv.organization | default(inventories.default.inv.organization) }}"
            state: "{{ item.inv.state | default(inventories.default.inv.state) }}"
          loop: "{{ inventories.data }}"
