- hosts: all
  gather_facts: false
  vars:
    issue_subject: "開発環境払い出し通知 {{ header_str }}"
    issue_desc: |
      開発環境の払い出しが完了しました。
      以下のURLとパスワードでアクセスしてください。

      ### 環境ID: {{ header_str }}
      {% if 'Jupyter Notebook' in IDE_TYPE %}
      ### Jupyter Lab
      {{ jupyter_url }}
      password: {{ jupyter_password }}
      {% endif %}

      {% if 'VSCode' in IDE_TYPE %}
      ### VSCode
      {{ vscode_url }}
      password: {{ vscode_password }}
      {% endif %}
  tasks:
    - uri:
        url: "{{ redmine_server_url + '/issues.json' }}"
        method: POST
        validate_certs: false
        headers:
          X-Redmine-API-Key: "{{ redmine_api_key }}"
        body_format: json
        body:
          issue:
            project_id: "{{ project_id }}"
            tracker_id: "{{ tracker_id }}"
            subject: "{{ issue_subject }}"
            description: "{{ issue_desc }}"
        return_content: yes
        status_code:
        - 200
        - 201
        timeout: "5"
      register: redmine_issue_search_result

    - debug: var=redmine_issue_search_result
    - debug: var=redmine_issue_search_result.json.issue.id

    - set_stats:
        data:
          ticket_id: "{{ redmine_issue_search_result.json.issue.id }}"

    - debug: var=ticket_id
