---
- name: waiting boot
  hosts: "tag_group_header_{{ header_str }}"
  gather_facts: false
  tasks:
    - name: Wait 300 seconds, but only start checking after 30 seconds
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
