---
- name: waiting boot
  hosts: all
  gather_facts: false
  tasks:
    - name: waiting instance boot
      ansible.builtin.ping:
      register: waiting_boot
      until: waiting_boot is not failed
      retries: 30
      delay: 10
