---
- hosts: localhost
  gather_facts: false
  vars:
    vmware_template_name: vm-27697
    vmware_folder_name: sandbox-9npbs
  tasks:

    - name: Start to clone a new VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          folder: group-v42928
        datastore: datastore-1031
        name: rhsc-demo-1
        source: vm-27697
        state: clone
      register: clone_vm_result

    - debug: var=clone_vm_result
