---
- hosts: localhost
  gather_facts: false
  vars:
    vmware_vm_name: rhel9-vm-1
  tasks:
    - name: Gather a VM info
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
          - "{{ vmware_vm_name }}"
      register: vm_info_result

    - debug: var=vm_info_result

    - name: Shut down the VM
      vmware.vmware_rest.vcenter_vm_guest_power:
        state: shutdown
        vm: '{{ vm_info_result.value[0].vm }}'
