---
- hosts: localhost
  gather_facts: false
  vars:
    vmware_vm_name: rhel9-vm-*
    vmware_folder_name: sandbox-9npbs
  tasks:
    - name: Gather a VM info
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
          - "{{ vmware_vm_name }}"
      register: vm_info_result

    - debug: var=vm_info_result

    - name: Gather a folder info
      vmware.vmware_rest.vcenter_folder_info:
        filter_names:
          - "{{ vmware_folder_name }}"
      register: folder_info_result

    - debug: var=folder_info_result
