---
- hosts: localhost
  gather_facts: false
  vars:
    vmware_template_name: vm-27697
    vmware_folder_name: sandbox-9npbs
  tasks:

    - name: Create A New VM From A Template
      vmware.vmware.deploy_folder_template:
        datacenter: "SDDC-Datacenter"
        vm_name: "rhsc2025-demo-1"
        template_name: "rhel94-tpl"
