---
- hosts: localhost
  gather_facts: false
  vars:
    vmware_folder_name: sandbox-9npbs
  tasks:
    - name: Gather a VM info
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
          - rhel9-vm-1
          - rhel9-vm-2
          - rhel9-vm-3
      register: vm_info_result

    - debug: var=vm_info_result
