---
- hosts: localhost
  gather_facts: false
  vars:
    vmware_template_name: vm-27697
    vmware_folder_name: sandbox-9npbs
  tasks:

    - name: Gather a folder info
      vmware.vmware_rest.vcenter_folder_info:
        filter_names:
          - "{{ vmware_folder_name }}"
      register: folder_info_result

    - debug: var=folder_info_result

    - name: Start to clone a new VM
      vmware.vmware_rest.vcenter_vm:
        placement:
          folder: "{{ folder_info_result.value.0.folder }}"
        name: rhsc-demo-1
        source: "{{ vmware_template_name }}"
        state: clone
      register: clone_vm_result

    - debug: var=clone_vm_result
