---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather a VM info
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
          - "{{ vmware_vm_name }}"
      register: vm_info_result

    - debug: var=vm_info_result

    - name: Startup the VM
      vmware.vmware_rest.vcenter_vm_power:
        state: start
        vm: '{{ vm_info_result.value[0].vm }}'
